//
//  ContributionsLeaderboard.swift
//  MySampleApp
//
//
// Copyright 2020 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class ContributionsLeaderboard: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _username: String?
    var _totalScore: NSNumber?
    var _puzzlesSubmitted: NSNumber?
    var _numBugReports: NSNumber?
    var _numBonuses: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "missinglink-mobilehub-2144505807-ContributionsLeaderboard"
    }
    
    class func hashKeyAttribute() -> String {

        return "_username"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_username" : "username",
            "_score" : "totalScore",
            "_submitted" : "puzzlesSubmitted",
            "_bugs" : "numBugReports",
            "_bonuses" : "numBonuses",
        ]
    }
    
    init(username: String, data: ContributionsData) {
        super.init()
        _username = username
        _totalScore = NSNumber(value: data.score)
        _puzzlesSubmitted = NSNumber(value: data.puzzlesSubmitted)
        _numBugReports = NSNumber(value: data.numBugReports)
        _numBonuses = NSNumber(value: data.numBonuses)
    }
    
    required init!(coder: NSCoder!) {
        super.init(coder: coder)
    }
    
    override init(dictionary dictionaryValue: [AnyHashable : Any]!, error: ()) throws {
        try super.init(dictionary: dictionaryValue, error: ())
    }
    
    override init!() {
        super.init()
    }
}
