//
//  PackData.swift
//  MySampleApp
//
//
// Copyright 2020 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class PackData: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _packName: String?
    var _data: String?
    var _packId: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "missinglink-mobilehub-2144505807-PackData"
    }
    
    class func hashKeyAttribute() -> String {

        return "_packName"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_packId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_packName" : "packName",
                "_packId" : "packId",
               "_data" : "data",
        ]
    }
    
    init(pack: PuzzlePack, id: Int) {
        super.init()
        _packName = pack.packName
        _packId = NSNumber(value: id)
        let encoder = JSONEncoder()
        let packAsData = try! encoder.encode(pack.getLevels())
        _data = String(data: packAsData, encoding: .utf8)
    }
    
    required init!(coder: NSCoder!) {
        super.init(coder: coder)
    }
    
    override init(dictionary dictionaryValue: [AnyHashable : Any]!, error: ()) throws {
        try super.init(dictionary: dictionaryValue, error: ())
    }
    
    override init!() {
        super.init()
    }
}
