//
//  UserProgress.swift
//  MySampleApp
//
//
// Copyright 2020 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB



@objcMembers class UserProgress: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _username: String?
    var _appProgress: String?
    var _userData: String?
    var _rewards: String?
    var _preferences: String?
    
    class func dynamoDBTableName() -> String {

        return "missinglink-mobilehub-2144505807-UserProgress"
    }
    
    class func hashKeyAttribute() -> String {

        return "_username"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_username" : "username",
            "_appProgress" : "app_progress",
            "_userData" : "user_data",
            "_rewards" : "rewards",
            "_preferences" : "preferences",
        ]
    }
        
    init(user: User) {
        super.init()
        
        _username = user.username
        
        let encoder = JSONEncoder()
        let progressAsData = try! encoder.encode(user.progress)
        _appProgress = String(data: progressAsData, encoding: .utf8)
        
        let userData = try! encoder.encode(user.data)
        _userData = String(data: userData, encoding: .utf8)
        
        let rewardsAsData = try! encoder.encode(user.rewards)
        _rewards = String(data: rewardsAsData, encoding: .utf8)
        
        let prefsAsData = try! encoder.encode(user.preferences)
        _preferences = String(data: prefsAsData, encoding: .utf8)
    }
    
    required init!(coder: NSCoder!) {
        super.init(coder: coder)
    }
    
    override init(dictionary dictionaryValue: [AnyHashable : Any]!, error: ()) throws {
        try super.init(dictionary: dictionaryValue, error: ())
    }
    
    override init!() {
        super.init()
    }
}
