//
//  UserAccounts.swift
//  MySampleApp
//
//
// Copyright 2020 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class UserAccounts: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _username: String?
    var _usernameSort: String?
    var _hash: String?
    
    class func dynamoDBTableName() -> String {

        return "missinglink-mobilehub-2144505807-UserAccounts"
    }
    
    class func hashKeyAttribute() -> String {

        return "_username"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_usernameSort"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_username" : "username",
            "_usernameSort" : "username_sort",
            "_hash" : "hash",
        ]
    }
        
    init(username: String, hash: String) {
        super.init()
        _username = username
        _usernameSort = username.uppercased()
        _hash = hash
    }
    
    required init!(coder: NSCoder!) {
        super.init(coder: coder)
    }
    
    override init(dictionary dictionaryValue: [AnyHashable : Any]!, error: ()) throws {
        try super.init(dictionary: dictionaryValue, error: ())
    }
    
    override init!() {
        super.init()
    }
}
