//
//  UserFeedback.swift
//  MySampleApp
//
//
// Copyright 2020 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class UserFeedback: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _category: String?
    var _time: String?
    var _user: String?
    var _feedback: String?
    
    class func dynamoDBTableName() -> String {

        return "missinglink-mobilehub-2144505807-UserFeedback"
    }
    
    class func hashKeyAttribute() -> String {

        return "_category"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_time"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_category" : "category",
               "_time" : "time",
               "_user" : "user",
               "_feedback" : "feedback",
        ]
    }
    
    init(source: FeedbackSource, now: Date, user: User, feedback: String) {
        super.init()
        _category = feedbackSourceData[source]
        setFeedbackDateFormat()
        _time = DATE_FORMATTER.string(from: now)
        // TODO: convert this to set beforehand every time OR create
        // separate formatters
        setDailyPuzzleDateFormat()
        _user = user.username
        _feedback = feedback
    }
    
    required init!(coder: NSCoder!) {
        super.init(coder: coder)
    }
    
    override init(dictionary dictionaryValue: [AnyHashable : Any]!, error: ()) throws {
        try super.init(dictionary: dictionaryValue, error: ())
    }
    
    override init!() {
        super.init()
    }
}
